Add error message

diff --git a/.github/workflows/deploy-to-aws-pull-request.yml b/.github/workflows/deploy-to-aws-pull-request.yml
--- a/.github/workflows/deploy-to-aws-pull-request.yml
+++ b/.github/workflows/deploy-to-aws-pull-request.yml
@@ -46,4 +46,9 @@ jobs:
         sudo systemctl enable tripplanner-itinerary
 
     - name: Verify service is running
-      run: systemctl status tripplanner-itinerary | grep "active (running)"
+      run: | 
+          if ! systemctl status tripplanner-itinerary | grep -q "active (running)"; then
+            systemctl status tripplanner-itinerary
+            echo "::error::Itinerary backend service encounters an error, check systemctl log to see what went wrong"
+            exit 1
+          fi
