Fix ci file

diff --git a/.github/workflows/deploy-to-aws-pull-request.yml b/.github/workflows/deploy-to-aws-pull-request.yml
--- a/.github/workflows/deploy-to-aws-pull-request.yml
+++ b/.github/workflows/deploy-to-aws-pull-request.yml
@@ -67,10 +67,8 @@ jobs:
 
     - name: Verify service is running
       run: |
-          sleep 5
-          systemctl status $SERVICE_NAME | grep "Active:"
-          if ! systemctl status $SERVICE_NAME | grep "active (running)"; then
-            systemctl status $SERVICE_NAME
-            echo "::error::Itinerary backend service encounters an error, check systemctl log to see what went wrong"
-            exit 1
-          fi
+          sleep 10
+          curl -f http://0.0.0.0:8000 || 
+          (echo "::error::Itinerary backend service encounters an error, check systemctl log to see what went wrong" &&
+            systemctl status $SERVICE_NAME &&
+            exit 1)
